# Generated by Django 3.0.1 on 2019-12-24 23:24

import core.models.adventure
from django.db import migrations
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_default_record_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='happened_at',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('draft', 'draft'), ('in_progress', 'in_progress'), ('finished', 'finished')], enum_class=core.models.adventure.AdventureStatus, max_length=11),
        ),
    ]
