# Generated by Django 3.0.1 on 2019-12-25 18:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adventure_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326),
        ),
    ]
