# Generated by Django 3.0.1 on 2019-12-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_record_elevation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='value',
        ),
    ]
