# Generated by Django 3.0.1 on 2020-01-01 19:12

import core.models.photo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_token_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.ImageField(null=True, upload_to=core.models.photo.Photo._upload_to_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Record'),
        ),
    ]
