FORMAT: 1A

# AdventureTracker API

Simple RESTful application interface implemented in [Django](https://www.djangoproject.com/) framework, which provide
storage & synchronization service for AdventureTracker mobile app. The application is aimed to nice & simple creation
of travel diaries.

## Version

Current version of API is `v1` and every endpoint HAVE TO contain version in the path.

## Identifiers

Because of synchronization and security reasons, we use
[UUID4](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_(random)) as unique identifiers of
dynamic records.

## Schema

All API requests should be transported using HTTPS. API supports these encodings (which are supplied in
`Accept` HTTP header):

- [MessagePack](https://msgpack.org/): `Accept: application/x-msgpack`
- [JSON](http://www.json.org): `Accept: application/json`

All variables and object properties in API are matching [snake_case](https://en.wikipedia.org/wiki/Snake_case)
convention.

### HTTP methods

| HTTP method | Description                |
|-------------|----------------------------|
| `GET`       | Accessing resource         |
| `POST`      | Creating new resource      |
| `PUT`       | Editing of resource        |
| `DELETE`    | Deleting resource          |

### Status codes

We use [HTTP Status Codes](https://http.cat/) to describe state of API response. Mostly we use these:

| HTTP code         | Description                                                              |
|-------------------|--------------------------------------------------------------------------|
| `200` `201` `204` | Success response                                                         |
| `401`             | Invalid user authentication (invalid credentials, inactive/blocked user) |
| `403`             | Insufficient permissions for action                                      |
| `404`             | Resource not found                                                       |
| `422`             | Validation error with program-readable metadata                          |
| `5xx`             | Internal server error (try it later)                                     |

## Date and time

All datetime information HAVE TO be represented as valid [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

## Response format

Response may contain `metadata` object with additional response data (for example pagination data). Format of metadata
is specified for each request. Mostly we use these properties:

- `page`: current page (counting from 1)
- `limit`: Maximum elements per page
- `pages`: Total number of pages
- `total`: Total number of records on all pages

### Simple response

```json
{
  "response": {
    "token": "PRETTY_AWESOME_TOKEN"
  }
}
```

### Pagination response

```json
{
  "items": [
    {
      "title": "Pigs",
      "artist": "Pink Floyd"
    },
    {
      "title": "Wish you were here",
      "artist": "Pink Floyd"
    }
  ],
  "metadata": {
    "page": 1,
    "limit": 2,
    "pages": 14,
    "total": 28
  }
}
```

### Error response

If status code is not `2xx` or `422`, API returns error response with description. Trace property is returned only in
debug mode of API.

```json
{
  "error": {
    "message": "Invalid permissions!",
    "trace": {}
  }
}
```

### Validation error

If status code of response is `422`, API returns validation error with detailed description. API always tries to return
as much validation errors as possible in one call to increase probability of success of next request.

```json
{
  "errors": {
    "title": [
      "Too short!",
      "Must contain a number."
    ],
    "artist": {
      "name": [
        "Must be present!"
      ]
    },
    "songs": [
      {
        "errors": {
          "title": "Must be present!"
        }
      }
    ]
  }
}
```

## Pagination and filtering

Pagination is controlled by these GET variables. Every paginated end-point is marked and supports these variables:

- `limit`: Maximum number of items per page
- `page`: Number of page (counting from 1)

## Data model

Data model is represented in EER diagram stored in file [AdventureTrackerApi.mwb](AdventureTrackerApi.mwb). We use
[PostgreSQL](https://www.postgresql.org/) with [PostGIS](https://postgis.net/) extension to store application data.

Default name for database is `adventuretracker_api` and data are stored in public schema.

# Group Authentication

## Authentication tokens [/v1/tokens]

### Create token [POST]

**Endpoint metadata**

| Description                | Value |
|----------------------------|-------|
| Requires signature         | True  |
| Requires authentication    | False |
| Pagination                 | False |
| Generates validation error | True  |

+ Request (application/json)
    + Attributes
        + username: `arthur.dent@gmail.com` (string, required) - User name in form of e-mail address.
        + password: `Hitchhiker42` (string, required) - Password
+ Response 201 (application/json)
    + Attributes (SingleResponse)
        + response (Token, required)
+ Response 422 (application/json)
    + Attributes (ValidationResponse)

## Validate authentication [/v1/auth/validate]

### Validate token [GET]

**Endpoint metadata**

| Description                | Value |
|----------------------------|-------|
| Requires signature         | True  |
| Requires authentication    | True  |
| Pagination                 | False |
| Generates validation error | False |

+ Response 200 (application/json)
    + Attributes (SingleResponse)
        + response (Token, required)

## Logout [/v1/auth/logout]

### Remove token [DELETE]

**Endpoint metadata**

| Description                | Value |
|----------------------------|-------|
| Requires signature         | True  |
| Requires authentication    | True  |
| Pagination                 | False |
| Generates validation error | False |

+ Response 204

# Group Sync

## Sync [/v1/sync]

### Sync device data [POST]

End-point vracia URL, na ktorej používateľ vykoná platbu a po jej vykonaní je následne presmerovaný naspäť do
XBionic API (špeciálneho webového rozhrania, viac informácii v GitLab Wiki).

**Endpoint metadata**

| Description                | Value |
|----------------------------|-------|
| Requires signature         | True  |
| Requires authentication    | True  |
| Pagination                 | False |
| Generates validation error | True  |

+ Request (application/json)
    + Attributes (SyncRequest)

+ Response 200 (application/json)
    + Attributes (SingleResponse)
        + response (SyncResponse, required)

+ Response 422 (application/json)
    + Attributes (ValidationResponse)

# Data Structures

## ErrorResponse (object)
+ error (object, required) - Error object
    - message: `Insufficient permissions for access to the resource!`: Description
    - trace (object) - Python exception trace (only for DEBUG environment)

## SingleResponse (object)
+ response (object, required) - Response object
+ metadata (object, required) - Metadata

## ValidationResponse (object)
+ errors (array, required) - Validation error objects

## ValidationError (object)
+ field: `email` (string, required) - Property name
+ details (array[string]) - Validation messages

## PaginationResponse (object)
+ items (array, required) - Response object
+ metadata (object, required) - Metadata
    - page: 1 (number, required) - Current page (counting from 1)
    - limit: 20 (number, required) - Maximum elements per page
    - pages: 2 (number, required) - Total number of pages
    - total: 26 (number, required) - Total number of records on all pages

## Token (object)
+ id: `1a58f3cf-68e3-495b-bf0a-d78bc8fb4b1f` (string, required) - Unique token identifier (UUID4)
+ user_id: `d59d3dd6-a1a1-4413-942e-5a3506046f6c` (string, required) - Token owner
+ expires_at: `2015-07-07T10:13:00+00:00` (string, nullable) - The expiration timestamp
+ created_at: `2019-12-26T08:25:50.211911+00:00` (string, required) - Timestamp of the creation

## RecordTypeResponse (object)
+ id: `71ccf8c1-87ad-47aa-8a24-3c7d571e7f69` (string, required) - Unique record type identifier
+ code: `camping` (string, required) - Unique record type code
+ title: `Camping` (string, required) - Localized record type title
+ description: `Campsite, nightstand or place where you stayed over night with place for a tent.` (string, required)
+ examples (array[string], required) - Localized example values

## Adventure (object)
+ id: `1a58f3cf-68e3-495b-bf0a-d78bc8fb4b1f` (string, required) - Unique adventure identifier (UUID4)
+ status (enum[string], required) - Adventure status
    + Default: `draft`

    + Members
        + `draft`
        + `in_progress`
        + `finished`

+ name: `Norway 2015` (string, required) - Adventure title
+ description: `A hitchhiking trip in Scandinavia` (string) - Description of the adventure
+ members (array[string]) - List of adventure members (email)
    - `845dd303-b1bf-4a5f-b1d7-4f4525ba5f4f`
    - `ac18a403-bd34-472d-b6c8-e7cac67dab5b`
+ started_at: `2015-07-07T10:13:00+00:00` (string, required) - Expected start of the adventure
+ finished_at: `2015-08-04T21:59:00+00:00` (string) - Expected end of the adventure

## AdventureSync (Adventure)
+ updated_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the last modification
+ records (array[AdventureRecordSync])

## AdventureResponse (Adventure)
+ created_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the creation
+ updated_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the last modification

## AdventureSyncResponse (AdventureResponse)
+ records (array[AdventureRecordResponse])

## Location (object)
+ latitude: 10.739527 (number, required) - GPS latitude
+ longitude: 59.927045 (number, required) - GPS longitude
+ altitude: 875.32 (number, required) - Altitude in meters

## AdventureRecord (object)
+ id: `1f718c33-adf9-43c6-9d82-28dc7bd4d9a4` (string, required) - Unique adventure record identifier (UUID4)
+ record_type_id: `00f248bb-e81a-41fc-9e18-74fc8e804499` (string, required) - Identifier of record type
+ user_id: `d59d3dd6-a1a1-4413-942e-5a3506046f6c` (string, required) - Creator ID (UUID4)
+ happened_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of record
+ description: `The weird nighstand on the bus stop` (string, required) - Record description
+ location (Location, required) - Location of the record

## AdventureRecordSync (AdventureRecord)
+ updated_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the last modification

## AdventureRecordResponse (AdventureRecord)
+ created_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the creation
+ updated_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the last modification

## User (object)
+ id: `1f718c33-adf9-43c6-9d82-28dc7bd4d9a4` (string, required) - Unique user identifier (UUID4)
+ email: `arthur.dent@gmail.com` (string, required) - User e-mail
+ name: `name` (string, required) - User name
+ surname: `surname` (string, required) - User surname

## UserResponse (User)
+ last_login: `2019-11-13T19:18:22+00:00` (string, required) - Last user login (token create)
+ created_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the creation
+ updated_at: `2019-11-13T19:18:22+00:00` (string, required) - Timestamp of the last modification

## SyncRequest (object)
+ last_sync: `2019-11-13T19:18:22+00:00` (string) - Timestamp of the last device synchronisation
+ user (User)
+ adventures (array[AdventureSync])

## SyncResponse
+ user (UserResponse)
+ adventures (array[AdventureSync])
+ record_types (array[RecordTypeResponse])
